```{r, echo=FALSE, include=FALSE}

RACE.rawweight  <-
  sqlQuery(channel,query = paste0("SELECT species_code, sex, weight FROM RACEBASE.SPECIMEN ((SPECIES_CODE = ",{{RACE}},"))"))

# Testing Line to Grab P.Cod
# RACE.rawweight  <-
#   sqlQuery(channel,query = paste0("SELECT SPECIES_CODE, SEX, WEIGHT FROM RACEBASE.SPECIMEN WHERE SPECIES_CODE = 232"))

evaltf <- ifelse(nrow(RACE.rawweight) > 0, TRUE, FALSE)

str0 <- "This Species does not have lengths in the database"

```

```{r include=FALSE, eval=evaltf}
#| label: var-{{RACE}}-{{NAME}}
RACE.rawweight2 <- na.omit(RACE.rawweight)
RACE.rawweight2 <- RACE.rawweight2[RACE.rawweight2$WEIGHT != 0, ]

race_wt.records <- nrow(RACE.rawweight2)


RACE.rawweight2$WEIGHT <- (RACE.rawweight2$WEIGHT / 1000)

race_wt.min <- min(RACE.rawweight2$WEIGHT)
race_wt.max <- max(RACE.rawweight2$WEIGHT)

race_wt.q2_5 <- quantile(x = RACE.rawweight2$WEIGHT, probs = 0.025, na.rm = TRUE)
race_wt.q97_5 <- quantile(x = RACE.rawweight2$WEIGHT, probs = 0.975, na.rm = TRUE)


str0 <- paste0("Number of records: **", 10, "**  
Minimum Weight: **", race_wt.min," kg**  |  Maximum Weight: **", race_wt.max," kg**  
95% Interval: **", race_wt.q2_5," kg** to **", race_wt.q97_5," kg**")

```

# Species: {{NAME}}
#### RACE DATA
`r str0`

```{r, echo=FALSE, eval=evaltf}
#| label: fig-second-{{RACE}}
#| fig-cap: 'RACE database weights for {{NAME}} as a percentage of recorded individuals. The shaded area is within the 95th percent confidence interval. '

race_wt.range <- race_wt.range %>%
  mutate(area = (avg_weight >= race_wt.q97_5 | avg_weight < race_wt.q2_5))

ggplot(data = race_wt.range, aes(x = avg_weight, y = percent)) +
  geom_line() +
  ylab("Percentage") +
  scale_x_continuous(breaks=number_ticks(10)) +
  xlab("Weight (kg)") +
  geom_ribbon(data = subset(race_wt.range, !(avg_weight >= race_wt.q97_5 | avg_weight <= race_wt.q2_5)),
              mapping = aes(ymax = percent), ymin = 0, fill = "red", alpha = 0.25, show.legend = FALSE) +
  theme_bw() +
  scale_y_continuous(labels = scales::percent_format(scale = 1))
```

<!-- ```{=tex} -->
<!-- \pagebreak -->
<!-- ``` -->